language: go

go:
  - 1.11.x
  - master

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest
  - golangci-lint --version

install:
  - go mod download

script:
  - make fmtcheck
  - make modcheck
  - make lint
  - make test
  - make test-race
  - make test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - go: master

notifications:
  email: false
